(function ensightenInit(){var ensightenOptions = {client: "hearst", clientId: 109, publishPath: "news-3p", bootstrapVersion: "v6_20201029", isPublic:0, serverComponentLocation: "/hearst/news-3p/serverComponent.php", staticJavascriptPath: "/hearst/news-3p/code/", ns: 'Bootstrapper', nexus:"", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Fri Nov 04 19:36:55 GMT 2022", beaconSamplingSeedValue: 11, dataLayerName: "ensDataLayer"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(h){function n(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function p(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function q(){for(var a=d.dataDefinitionIds.length,b=!0,e=0;e<a;e++){var f=d.dataDefinitions[d.dataDefinitionIds[e]];if(!f||
null==f.endRegistration){b=!1;break}}b&&d.callOnDataDefintionComplete()}var c={},d={};d.ensightenOptions=ensightenOptions;d.scDataObj={};c.version="1.26.0";c.getDynamicDomain=function(){for(var a=null,b=document.getElementsByTagName("script"),e=h.client+"/"+h.publishPath+"/Bootstrap.js",f=h.client+"/Bootstrap.js",g=0;g<b.length;g++)if(-1<b[g].src.indexOf(e)||"prod"==h.publishPath&&-1<b[g].src.indexOf(f)){a=b[g];break}return a?(b=document.createElement("a"),b.href=a.getAttribute("src"),b.hostname):
""};ensightenOptions.nexus=c.nexus=ensightenOptions.nexus||c.getDynamicDomain()||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:h.interval||100,erLoc:h.errorLocation||c.nexus+"/error/e.gif",scLoc:h.serverComponentLocation||c.nexus+"/"+h.client+"/serverComponent.php",sjPath:h.staticJavascriptPath||c.nexus+"/"+h.client+"/code/",alLoc:h.alertLocation||c.nexus+"/alerts/a.gif",publishPath:h.publishPath,isPublic:h.isPublic,client:h.client,clientId:h.clientId,enableTagAuditBeacon:h.enableTagAuditBeacon,
beaconSamplingSeedValue:h.beaconSamplingSeedValue||-1,dataLayerName:h.dataLayerName||"ensDataLayer"};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.appIdWhitelist=[];c.appIdBlacklist=[];window[c.options.dataLayerName]&&window[c.options.dataLayerName][0]&&(window[c.options.dataLayerName][0]["ens.whitelist"]&&(c.appIdWhitelist=window[c.options.dataLayerName][0]["ens.whitelist"]),window[c.options.dataLayerName][0]["ens.blacklist"]&&
(c.appIdBlacklist=window[c.options.dataLayerName][0]["ens.blacklist"]));c.canRuleRunByAppId=function(a){return a?a&&!a.appId||a&&-1==a.appId||0==c.appIdWhitelist.length&&0==c.appIdBlacklist.length?!0:0<c.appIdWhitelist.length&&0==c.appIdBlacklist.length?-1==c.appIdWhitelist.indexOf(a.appId)?!1:!0:0==c.appIdWhitelist.length&&0<c.appIdBlacklist.length?-1==c.appIdBlacklist.indexOf(a.appId)?!0:!1:0<c.appIdWhitelist.length&&0<c.appIdBlacklist.length&&-1==c.appIdBlacklist.indexOf(a.appId)&&-1!=c.appIdWhitelist.indexOf(a.appId)?
!0:!1:!1};c.test=function(a){if(c.canRuleRunByAppId(a)&&!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.DependencyNotAvailableException=n;p.prototype=Error();p.prototype||(p.prototype={});p.prototype.constructor=p;c.BeaconException=p;c.checkForInvalidDependencies=function(a,b,e,f){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===
e[a])return d.currentRuleId=this.id,d.currentDeploymentId=this.deploymentId,d.reportException(new c.DependencyNotAvailableException(f[a])),b&&-1!==b&&c.allDeploymentIds.push(b),!0;return!1};d.currentRuleId=-1;d.currentDeploymentId=-1;d.reportedErrors=[];d.reportedAlerts=[];d.AF=[];d._serverTime="";d._clientIP="";d.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,e=c.options.beaconSamplingSeedValue;-1===e?a=!0:0!==b&&0===e%b&&(a=!0)}catch(f){}return a};d.getServerComponent=function(a){d.callOnGetServerComponent();
var b=window.location.protocol+"//"+("/"==c.options.scLoc.charAt(0)?c.getDynamicDomain():"")+c.options.scLoc;d.insertScript(b,!1,a||!0)};d.setVariable=function(a,b){c.ensightenVariables[a]=b};d.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};d.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};d.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};d.reportException=function(a){a.timestamp=
(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(d.currentRuleId||-1)+"&did="+encodeURIComponent(d.currentDeploymentId||-1)+"&errorName="+
encodeURIComponent(a.name||"");a=d.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};d.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);d.currentRuleId=this.id;d.currentDeploymentId=this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),d.testAll()}};this.id=a.id;this.deploymentId=
a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.appId=a.appId;this.executionData={hasRun:!1,runTime:[]}};d.registerRule=function(a){if(d.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);d.testAll();return!0};d.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};d.getRuleList=function(){return c.ruleList};d.clearRuleList=function(){c.ruleList=[]};d.getAllDeploymentIds=
function(){return c.allDeploymentIds};d.getRunRuleIds=function(){return c.runRuleIds};d.getRunDeploymentIds=function(){return c.runDeploymentIds};d.hasRuleRun=function(a){return(a=d.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};d.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=
a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};d.generateAlert=function(a){a=d.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+
d.currentRuleId+"&did="+d.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};d.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};d.insertScript=function(a,b,e){var f=document.getElementsByTagName("script"),g;if(void 0!==b?b:1)for(g=0;g<f.length;g++)if(f[g].src===a&&f[g].readyState&&/loaded|complete/.test(f[g].readyState))return;if(e){e=1==e&&"object"==typeof d.scDataObj?d.scDataObj:e;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;
"object"===typeof e&&e.PageID&&(b=e.PageID,delete e.PageID);if("object"===typeof e)for(g in e){g=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,g.length?b.length-g.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in e)b+=k+"="+e[k]+"&";b=b.slice(0,-1)+g;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="publishedOn="+ensightenOptions.generatedOn+"&";a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(b)+
("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")}(function(l,m,r){var t=m.head||m.getElementsByTagName("head");setTimeout(function(){if("item"in t){if(!t[0]){setTimeout(arguments.callee,25);return}t=t[0]}var u=m.createElement("script");u.src=r;u.onload=u.onerror=function(){this.addEventListener&&(this.readyState="loaded")};t.insertBefore(u,t.firstChild)},0)})(window,document,a)};d.loadScriptCallback=function(a,b,e){var f=document.getElementsByTagName("script"),g=f[0];if(e)for(e=
0;e<f.length;e++)if(f[e].src===a&&f[e].readyState&&/loaded|complete/.test(f[e].readyState))try{b()}catch(l){window[ensightenOptions.ns].reportException(l)}finally{return}f=document.createElement("script");f.type="text/javascript";f.async=!0;f.src=a;f.onerror=function(){this.addEventListener&&(this.readyState="loaded")};f.onload=f.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(l){window[ensightenOptions.ns].reportException(l)}}};g.parentNode.insertBefore(f,g)};d.insertPageFiles=function(a){var b=0,e=0,f=function(){e==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();e++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],f)};d.unobtrusiveAddEvent=function(a,b,e){try{var f=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return f.apply(this,arguments)}}catch(g){window[ensightenOptions.ns].reportException(g)}};
d.anonymous=function(a,b){return function(){try{d.currentRuleId=b?b:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};d.setCurrentRuleId=function(a){d.currentRuleId=a};d.setCurrentDeploymentId=function(a){d.currentDeploymentId=a};c.bind=function(a,b,e,f,g){if("function"===typeof a)a=new d.Rule({id:b||-1,deploymentId:e||-1,appId:f||-1,dependencies:"immediate"==g?[]:[function(){return window[ensightenOptions.ns].executionState[g]}],code:a});else if("object"!==typeof a)return!1;
d.registerRule(a)};d.bindImmediate=function(a,b,e,f){c.bind(a,b,e,f,"immediate")};d.bindDOMParsed=function(a,b,e,f){c.bind(a,b,e,f,"DOMParsed")};d.bindDOMLoaded=function(a,b,e,f){c.bind(a,b,e,f,"DOMLoaded")};d.bindPageSpecificCompletion=function(a,b,e,f){c.bind(a,b,e,f,"conditionalRules")};d.bindOnGetServerComponent=function(a,b,e,f){c.bind(a,b,e,f,"readyForServerComponent")};d.bindDataDefinitionComplete=function(a,b,e,f){c.bind(a,b,e,f,"dataDefinitionComplete")};d.checkHasRun=function(a){if(0===
a.length)return!0;for(var b,e=0;e<a.length;++e)if(b=d.getRule(parseInt(a[e],10)),!b||!b.executionData.hasRun)return!1;return!0};c.bindDependency=function(a,b,e,f,g,l,m){var r=[];if(!c.checkForInvalidDependencies(b,f,e,g)){"immediate"==!m&&r.push(function(){return window[ensightenOptions.ns].executionState[m]});r.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new d.Rule({id:b||-1,deploymentId:f||-1,appId:l||-1,dependencies:r,code:a});else if("object"!==
typeof a)return!1;d.registerRule(a)}};d.bindDependencyImmediate=function(a,b,e,f,g,l){c.bindDependency(a,b,e,f,g,l,"immediate")};d.bindDependencyDOMLoaded=function(a,b,e,f,g,l){c.bindDependency(a,b,e,f,g,l,"DOMLoaded")};d.bindDependencyDOMParsed=function(a,b,e,f,g,l){c.bindDependency(a,b,e,f,g,l,"DOMParsed")};d.bindDependencyPageSpecificCompletion=function(a,b,e,f,g,l){c.bindDependency(a,b,e,f,g,l,"conditionalRules")};d.bindDependencyOnGetServerComponent=function(a,b,e,f,g,l){c.bindDependency(a,b,
e,f,g,l,"readyForServerComponent")};d.bindDependencyDataDefinitionComplete=function(a,b,e,f,g,l){c.bindDependency(a,b,e,f,g,l,"dataDefinitionComplete")};d.dataDefintionIds=[];d.dataDefinitions=[];d.pageSpecificDataDefinitionsSet=!1;d.setPageSpecificDataDefinitionIds=function(a){for(var b=a?a.length:0,e=0;e<b;e++){var f=a[e];if(Array.prototype.indexOf)-1==d.dataDefinitionIds.indexOf(f)&&d.dataDefinitionIds.push(f);else{for(var g=!1,l=d.dataDefinitionIds.length,m=0;m<l;m++)if(d.dataDefinitionIds[m]===
f){g=!0;break}g||d.dataDefinitionIds.push(f)}}d.pageSpecificDataDefinitionsSet=!0;q()};d.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};d.registerDataDefinition=function(a,b){var e=d.dataDefinitions[b];e||(e=new d.DataDefinition(b,a),d.dataDefinitions[b]=e);e.startRegistrationTime||(e.startRegistration(),
e.registrationFn(),e.endRegistration());d.pageSpecificDataDefinitionsSet&&q()};d.callOnDataDefintionComplete=function(){d.executionState.dataDefinitionComplete=!0;d.testAll()};d.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};d.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};d.callOnPageSpecificCompletion=
function(){for(var a=document.getElementsByTagName("script"),b=0,e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};d.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=
!0;window[ensightenOptions.ns].testAll()};d.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};d.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};d.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var v=function(){var a=[],b=!1,e=!1;return{add:function(f){b&&!e?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){e=!0;do{var f=a;a=[];b=!0;for(var g=0;g<f.length;g++)try{f[g].call(window)}catch(l){window[ensightenOptions.ns].reportException(l)}}while(0<
a.length);e=!1},haveRun:function(){return b}}};d.new_fArray=function(){return v()};c.timer=null;(function(){function a(f,g){return function(){f.apply(g,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var e=log4javascript.getDefaultLogger();b.log=a(e.info,e);b.debug=a(e.debug,e);b.info=a(e.info,e);b.warn=a(e.warn,e);b.error=a(e.error,e)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=
b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),d.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",d.callOnDOMParsed,!1),window.addEventListener("load",d.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,
15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(d.executionState.DOMParsed=!0,d.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&d.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,e,f,g,l=0;l<c.ruleList.length;++l)e=c.ruleList[l],
f=e.executionData.hasRun?"1":"0",g=e.deploymentId.toString()+"|"+e.id.toString()+"|"+f,a.push(g);b="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(h.client)+"/"+encodeURIComponent(h.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(h.clientId)+"&data="+b+"&idx=0&r="+c.rand;d.imageRequest(m)}catch(r){d.currentRuleId=-1,d.currentDeploymentId=-1,a=new c.BeaconException(r),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(d.testAll,
c.options.interval);return d}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var h=window.performance;if(h){h=h.timing||{};var n=h.navigationStart||0,p={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var q="&ns="+encodeURIComponent(h.navigationStart);for(var c in p)if(void 0!==h[c]){var d=h[c]-n;q+="&"+p[c]+"="+(0<d?encodeURIComponent(d):0)}else q+="&"+p[c]+"=-1";window[ensightenOptions.ns].timing=q;c=ensightenOptions.nexus||"nexus.ensighten.com";h=ensightenOptions.staticJavascriptPath||
"";q=h.indexOf("/",0);n=h.indexOf("/code/");h=h.substring(q,n)+"/perf.rnc";h+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+h)}}});

  window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(p,u){var k={queue:{},pollQueue:{},pushTrigger:function(a,c){if("[object Array]"===Object.prototype.toString.call(a)){for(var g=0;g<a.length;g++)k.pushTrigger(a[g],c);return!0}if("string"!=typeof a)return!1;this.queue[a]=this.queue[a]||{fn:[]};"function"==typeof c&&this.queue[a].fn.push(c);return!0},callTrigger:function(a,c,g){if("string"!=typeof a)return!1;a=k.queue[a];if("object"==typeof a&&a.fn&&a.fn.length&&(0!=
  a.fireOnFirstSet&&c==u||c!=u&&0!=a.fireOnUpdate))for(c=0;c<a.fn.length;c++)try{a.fn[c].call(this)}catch(n){p[ensightenOptions.ns].reportException(n)}},setPollOptions:function(a,c,g){this.queue[a]=this.queue[a]||{fn:[]};this.queue[a].fireOnFirstSet=c;this.queue[a].fireOnUpdate=g},callPoll:function(a,c,g,p,r){if("string"==typeof a&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)k.setPollOptions(c[n],p,r);k.pushWatch(a,c,g)}},pushWatch:function(a,c,g){this.pollQueue[a]||(this.pollQueue[a]={previousVal:u,
  eventArr:[],valueFn:g});this.pollQueue[a].eventArr=this.pollQueue[a].eventArr.concat(c);this.pollQueue[a].valueFn=g},globalWatch:function(){setInterval(function(){for(var a in k.pollQueue){var c=k.pollQueue[a],g=c.valueFn(a);if(c.previousVal!==g&&null!==g&&""!==g){for(var n=0;n<c.eventArr.length;n++)k.callTrigger.call(p,c.eventArr[n],c.previousVal,g);k.pollQueue[a].previousVal=g}}},500)}};k.globalWatch();return{add:function(a,c){return k.pushTrigger(a,c)},get:function(a){return k.queue[a]},trigger:function(a,
  c){return k.callTrigger.call(c||p,a)},poll:function(a,c,g,n,r){r=r||p[ensightenOptions.ns].data.resolve;return k.callPoll(a,c,r,g,n)}}}(window),function(p,u,k){u[p]=k()}("qwery",window[ensightenOptions.ns],function(){function p(){this.c={}}function u(b){return H.g(b)||H.s(b,"(^|\\s+)"+b+"(\\s+|$)",1)}function k(b,d){for(var e=0,f=b.length;e<f;e++)d(b[e])}function a(b){for(var d=[],e=0,f=b.length;e<f;++e)l(b[e])?d=d.concat(b[e]):d[d.length]=b[e];return d}function c(b){for(var d=0,e=b.length,f=[];d<
  e;d++)f[d]=b[d];return f}function g(b){for(;(b=b.previousSibling)&&1!=b.nodeType;);return b}function n(b,d,e,f,a,h,l,c,g,k,y){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(b=m.length;b--;)if(!u(m[b].slice(1)).test(this.className))return!1;if(g&&v.pseudos[g]&&!v.pseudos[g](this,y))return!1;if(f&&!l)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==
  a)return this;return f&&!x(h,S(this,a)||"",l)?!1:this}function r(b){return J.g(b)||J.s(b,b.replace(T,"\\$1"))}function x(b,d,e){switch(b){case "=":return d==e;case "^=":return d.match(w.g("^="+e)||w.s("^="+e,"^"+r(e),1));case "$=":return d.match(w.g("$="+e)||w.s("$="+e,r(e)+"$",1));case "*=":return d.match(w.g(e)||w.s(e,r(e),1));case "~=":return d.match(w.g("~="+e)||w.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(w.g("|="+e)||w.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function q(b,
  d){var e=[],f=[],a,h,l=d,c=C.g(b)||C.s(b,b.split(K)),g=b.match(L);if(!c.length)return e;var m=(c=c.slice(0)).pop();c.length&&(a=c[c.length-1].match(M))&&(l=N(d,a[1]));if(!l)return e;var y=m.match(E);var v=l!==d&&9!==l.nodeType&&g&&/^[+~]$/.test(g[g.length-1])?function(b){for(;l=l.nextSibling;)1==l.nodeType&&(y[1]?y[1]==l.tagName.toLowerCase():1)&&(b[b.length]=l);return b}([]):l.getElementsByTagName(y[1]||"*");a=0;for(m=v.length;a<m;a++)if(h=n.apply(v[a],y))e[e.length]=h;if(!c.length)return e;k(e,
  function(b){t(b,c,g)&&(f[f.length]=b)});return f}function t(b,d,e,a){function l(b,a,c){for(;c=U[e[a]](c,b);)if(f(c)&&n.apply(c,d[a].match(E)))if(a){if(h=l(c,a-1,c))return h}else return c}var h;return(h=l(b,d.length-1,b))&&(!a||z(h,a))}function f(b,d){return b&&"object"===typeof b&&(d=b.nodeType)&&(1==d||9==d)}function h(b){var d=[],e;var f=0;a:for(;f<b.length;++f){for(e=0;e<d.length;++e)if(d[e]==b[f])continue a;d[d.length]=b[f]}return d}function l(b){return"object"===typeof b&&isFinite(b.length)}
  function N(b,d,e){return 9===b.nodeType?b.getElementById(d):b.ownerDocument&&((e=b.ownerDocument.getElementById(d))&&z(e,b)&&e||!z(b,b.ownerDocument)&&F('[id="'+d+'"]',b)[0])}function v(b,d){var e,h;var g=d?"string"==typeof d?v(d)[0]:!d.nodeType&&l(d)?d[0]:d:m;if(!g||!b)return[];if(b===window||f(b))return!d||b!==window&&f(g)&&z(b,g)?[b]:[];if(b&&l(b))return a(b);if(e=b.match(V)){if(e[1])return(h=N(g,e[1]))?[h]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(b,
  g)}function y(b,d){return function(e){var f,a;O.test(e)?9!==b.nodeType&&((a=f=b.getAttribute("id"))||b.setAttribute("id",a="__qwerymeupscotty"),d(b.parentNode||b,'[id="'+a+'"]'+e,!0),f||b.removeAttribute("id")):e.length&&d(b,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+~>]|$)\s*/g,A=/[\s>\+~]/,P=/(?![\s\w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,
  V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*~]?=)['"]?([ \w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(b){return b&&b!==D&&b.parentNode},">":function(b,d){return b&&b.parentNode==d.parentNode&&b.parentNode},"~":function(b){return b&&
  b.previousSibling},"+":function(b,d,e,f){return b?(e=g(b))&&(f=g(d))&&e==f&&e:!1}};p.prototype={g:function(b){return this.c[b]||void 0},s:function(b,d,e){d=e?new RegExp(d):d;return this.c[b]=d}};var H=new p,J=new p,w=new p,C=new p,z="compareDocumentPosition"in D?function(b,d){return 16==(d.compareDocumentPosition(b)&16)}:"contains"in D?function(b,d){d=9===d.nodeType||d==window?D:d;return d!==b&&d.contains(b)}:function(b,d){for(;b=b.parentNode;)if(b===d)return 1;return 0},S=function(){var b=m.createElement("p");
  return(b.innerHTML='<a href="#x">x</a>',"#x"!=b.firstChild.getAttribute("href"))?function(b,e){return"class"===e?b.className:"href"===e||"src"===e?b.getAttribute(e,2):b.getAttribute(e)}:function(b,e){return b.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(b,d){var e=[],f,a;try{if(9===d.nodeType||!O.test(b))return c(d.querySelectorAll(b));k(f=b.split(","),y(d,function(b,d){a=b.querySelectorAll(d);1==a.length?e[e.length]=a.item(0):a.length&&(e=e.concat(c(a)))}));
  return 1<f.length&&1<e.length?h(e):e}catch(ba){}return G(b,d)},G=function(b,d){var e=[],f,a;b=b.replace(Y,"$1");if(f=b.match(X)){var l=u(f[2]);f=d.getElementsByTagName(f[1]||"*");var c=0;for(a=f.length;c<a;c++)l.test(f[c].className)&&(e[e.length]=f[c]);return e}k(f=b.split(","),y(d,function(b,f,h){l=q(f,b);c=0;for(a=l.length;c<a;c++)if(9===b.nodeType||h||z(l[c],d))e[e.length]=l[c]}));return 1<f.length&&1<e.length?h(e):e};A=function(b){"undefined"!==typeof b.useNativeQSA&&(F=b.useNativeQSA?Z?aa:G:
  G)};A({useNativeQSA:!0});v.configure=A;v.uniq=h;v.is=function(b,d,e){if(f(d))return b==d;if(l(d))return!!~a(d).indexOf(b);for(var c=d.split(","),h;d=c.pop();)if(h=C.g(d)||C.s(d,d.split(K)),d=d.match(L),h=h.slice(0),n.apply(b,h.pop().match(E))&&(!h.length||t(b,h,d,e)))return!0;return!1};v.pseudos={};return v}),function(){function p(f,a,c){n||(n=window[ensightenOptions.ns].qwery);var h=n;if((h=h.call(c,a,c))&&0<h.length){if("_root"==a)f=c;else if(f===c)f=void 0;else{b:{for(var l=h.length,g=0;g<l;g++)if(f===
  h[g]){h=!0;break b}h=!1}h||(f.parentNode?(r++,f=p(f.parentNode,a,c)):f=void 0)}return f}return!1}function u(f,a,c,g){q[f.id]||(q[f.id]={});q[f.id][a]||(q[f.id][a]={});q[f.id][a][c]||(q[f.id][a][c]=[]);q[f.id][a][c].push(g)}function k(f,a,c,g){if(g||c)if(g)for(var h=0;h<q[f.id][a][c].length;h++){if(q[f.id][a][c][h]===g){q[f.id][a][c].pop(h,1);break}}else delete q[f.id][a][c];else q[f.id][a]={}}function a(a,c,l){if(q[a][l]){var f=c.target||c.srcElement,h,k,m={},n=k=0;r=0;for(h in q[a][l])q[a][l].hasOwnProperty(h)&&
  (k=p(f,h,t[a].element))&&g.matchesEvent(l,t[a].element,k,"_root"==h,c)&&(r++,q[a][l][h].match=k,m[r]=q[a][l][h]);c.stopPropagation=function(){c.cancelBubble=!0};for(k=0;k<=r;k++)if(m[k])for(n=0;n<m[k].length;n++){if(!1===m[k][n].call(m[k].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(c,h,l,n){function f(c){return function(f){a(p,f,c)}}c instanceof Array||(c=[c]);l||"function"!=typeof h||(l=h,h="_root");var p=this.id,m;for(m=0;m<c.length;m++)q[p]&&q[p][c[m]]||g.addEvent(this,c[m],
  f(c[m])),n?k(this,c[m],h,l):u(this,c[m],h,l);return this}function g(a,c,l,k){if("string"==typeof a&&"function"==typeof c||"string"==typeof c)g(document).on(a,c,l,k||!1);if(!(this instanceof g)){for(var f in t)if(t[f].element===a)return t[f];x++;t[x]=new g(a,x);t[x]._on=t[x].on;t[x].on=function(a,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)a=[a],"string"==typeof c&&a.push(c),a.push(function(a){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);
  if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return a.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;a.call(this)}}(h)),this._on.apply(this,a);else return this._on.call(this,a,c,f)};return t[x]}this.element=a;this.id=c}var n,r=0,x=0,q={},t={};g.prototype.on=function(a,g,l){return c.call(this,a,g,l)};g.prototype.off=function(a,g,l){return c.call(this,a,g,l,!0)};g.cancel=function(a){a.preventDefault();a.stopPropagation()};g.addEvent=function(a,c,g){a.element.addEventListener(c,
  g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(a){setTimeout(function(a,c){var f=a.getAttribute("target")||"_self";return function(){if(a.nodeName&&"a"==a.nodeName.toLowerCase()){if(c&&/^javascript\s*:/.test(c))return(new Function(unescape(c))).call(window);c&&window.open(c,f)}}}(a,a.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(p){var u=p.addEvent;p.addEvent=function(k,a,c){if(k.element.addEventListener)return u(k,a,c);"focus"==a&&(a="focusin");
  "blur"==a&&(a="focusout");k.element.attachEvent("on"+a,c)};p.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;"use strict";(function(win){var version="1.0";var ofs="offset",cl="client";var noop=function(){};var testedOnce=false;var testExecuting=false;var isOldIEevents=win.addEventListener===undefined;var _options={loopDelay:50,maxLoop:1,debug:false,found:noop,notfound:noop,complete:noop};function parseAsJson(data){var result,fnData;try{result=JSON.parse(data)}catch(ex){try{fnData=
new Function("return "+data);result=fnData()}catch(ex){log("Failed secondary JSON parse",true)}}return result}var AjaxHelper=function(opts){var xhr=new XMLHttpRequest;this.success=opts.success||noop;this.fail=opts.fail||noop;var me=this;var method=opts.method||"get";this.abort=function(){try{xhr.abort()}catch(ex){}};function stateChange(vals){if(xhr.readyState==4)if(xhr.status==200)me.success(xhr.response);else me.fail(xhr.status)}xhr.onreadystatechange=stateChange;function start(){xhr.open(method,
opts.url,true);xhr.send()}start()};var BlockListTracker=function(){var me=this;var externalBlocklistData={};this.addUrl=function(url){externalBlocklistData[url]={url:url,state:"pending",format:null,data:null,result:null};return externalBlocklistData[url]};this.setResult=function(urlKey,state,data){var obj=externalBlocklistData[urlKey];if(obj===null)obj=this.addUrl(urlKey);obj.state=state;if(data===null){obj.result=null;return}if(typeof data==="string")try{data=parseAsJson(data);obj.format="json"}catch(ex){obj.format=
"easylist"}obj.data=data;return obj}};var listeners=[];var baitNode=null;var quickBait={cssClass:"pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links"};var baitTriggers={nullProps:[ofs+"Parent"],zeroProps:[]};baitTriggers.zeroProps=[ofs+"Height",ofs+"Left",ofs+"Top",ofs+"Width",ofs+"Height",cl+"Height",cl+"Width"];var exeResult={quick:null,remote:null};var findResult=null;var timerIds={test:0,download:0};function isFunc(fn){return typeof fn=="function"}function makeEl(tag,
attributes){var k,v,el,attr=attributes;var d=document;el=d.createElement(tag);if(attr)for(k in attr)if(attr.hasOwnProperty(k))el.setAttribute(k,attr[k]);return el}function attachEventListener(dom,eventName,handler){if(isOldIEevents)dom.attachEvent("on"+eventName,handler);else dom.addEventListener(eventName,handler,false)}function log(message,isError){if(!_options.debug&&!isError)return;if(win.console&&win.console.log)if(isError)console.error("[ABD] "+message);else console.log("[ABD] "+message)}var ajaxDownloads=
[];function loadExecuteUrl(url){var ajax,result;blockLists.addUrl(url);ajax=new AjaxHelper({url:url,success:function(data){log("downloaded file "+url);result=blockLists.setResult(url,"success",data);try{var intervalId=0,retryCount=0;var tryExecuteTest=function(listData){if(!testExecuting){beginTest(listData,true);return true}return false};if(findResult===true)return;if(tryExecuteTest(result.data))return;else{log("Pause before test execution");intervalId=setInterval(function(){if(tryExecuteTest(result.data)||
retryCount++>5)clearInterval(intervalId)},250)}}catch(ex){log(ex.message+" url: "+url,true)}},fail:function(status){log(status,true);blockLists.setResult(url,"error",null)}});ajaxDownloads.push(ajax)}function fetchRemoteLists(){var i,url;var opts=_options;for(i=0;i<opts.blockLists.length;i++){url=opts.blockLists[i];loadExecuteUrl(url)}}function cancelRemoteDownloads(){var i,aj;for(i=ajaxDownloads.length-1;i>=0;i--){aj=ajaxDownloads.pop();aj.abort()}}function beginTest(bait){log("start beginTest");
if(findResult===true)return;testExecuting=true;castBait(bait);exeResult.quick="testing";timerIds.test=setTimeout(function(){reelIn(bait,1)},5)}function castBait(bait){var i,d=document,b=d.body;var t;var baitStyle="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;";if(bait===null||typeof bait=="string"){log("invalid bait being cast");return}if(bait.style!==null)baitStyle+=bait.style;baitNode=makeEl("div",{"class":bait.cssClass,
"style":baitStyle});log("adding bait node to DOM");b.appendChild(baitNode);for(i=0;i<baitTriggers.nullProps.length;i++)t=baitNode[baitTriggers.nullProps[i]];for(i=0;i<baitTriggers.zeroProps.length;i++)t=baitNode[baitTriggers.zeroProps[i]]}function reelIn(bait,attemptNum){var i,k,v;var body=document.body;var found=false;if(baitNode===null){log("recast bait");castBait(bait||quickBait)}if(typeof bait=="string"){log("invalid bait used",true);if(clearBaitNode())setTimeout(function(){testExecuting=false},
5);return}if(timerIds.test>0){clearTimeout(timerIds.test);timerIds.test=0}if(body.getAttribute("abp")!==null){log("found adblock body attribute");found=true}for(i=0;i<baitTriggers.nullProps.length;i++){if(baitNode[baitTriggers.nullProps[i]]===null){found=true;log("found adblock null attr: "+baitTriggers.nullProps[i]);break}if(found===true)break}for(i=0;i<baitTriggers.zeroProps.length;i++){if(found===true)break;if(baitNode[baitTriggers.zeroProps[i]]===0){found=true;log("found adblock zero attr: "+
baitTriggers.zeroProps[i])}}if(window.getComputedStyle!==undefined){var baitTemp=window.getComputedStyle(baitNode,null);if(baitTemp.getPropertyValue("display")=="none"||baitTemp.getPropertyValue("visibility")=="hidden"){found=true;log("found adblock computedStyle indicator")}}testedOnce=true;if(found||attemptNum++>=_options.maxLoop){findResult=found;log("exiting test loop - value: "+findResult);notifyListeners();if(clearBaitNode())setTimeout(function(){testExecuting=false},5)}else timerIds.test=setTimeout(function(){reelIn(bait,
attemptNum)},_options.loopDelay)}function clearBaitNode(){if(baitNode===null)return true;try{if(isFunc(baitNode.remove))baitNode.remove();document.body.removeChild(baitNode)}catch(ex){}baitNode=null;return true}function stopFishing(){if(timerIds.test>0)clearTimeout(timerIds.test);if(timerIds.download>0)clearTimeout(timerIds.download);cancelRemoteDownloads();clearBaitNode()}function notifyListeners(){var i,funcs;if(findResult===null)return;for(i=0;i<listeners.length;i++){funcs=listeners[i];try{if(funcs!==
null){if(isFunc(funcs["complete"]))funcs["complete"](findResult);if(findResult&&isFunc(funcs["found"]))funcs["found"]();else if(findResult===false&&isFunc(funcs["notfound"]))funcs["notfound"]()}}catch(ex){log("Failure in notify listeners "+ex.Message,true)}}}function attachOrFire(){var fireNow=true;var fn;fn=function(){beginTest(quickBait,false)};if(fireNow)fn();else attachEventListener(win,"load",fn)}var blockLists;var impl={version:version,init:function(options){var k,v,funcs;if(!options)return;
funcs={complete:noop,found:noop,notfound:noop};for(k in options)if(options.hasOwnProperty(k))if(k=="complete"||k=="found"||k=="notFound")funcs[k.toLowerCase()]=options[k];else _options[k]=options[k];listeners.push(funcs);blockLists=new BlockListTracker;attachOrFire()}};win["abd"]=impl})(window);function getCookie(name){var nameEQ=name+"\x3d",ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0){var result=
c.substring(nameEQ.length,c.length);return result}}return""}function setCookie(name,value,minutes){var expDate=new Date,cookieValue;expDate.setDate(expDate.getDate());expDate.setMinutes(expDate.getMinutes()+minutes);cookieValue=value+(minutes===null?"":";expires\x3d"+expDate.toUTCString()+"; path\x3d/");document.cookie=name+"\x3d"+cookieValue}function updateCookie(name,abstatus,minutes){var cookieObj={},cookie=getCookie(name);if(cookie)cookieObj=JSON.parse(cookie);else{cookieObj.first=abstatus;cookieObj.test=
"";cookieObj.result=""}cookieObj.last=abstatus;var cookieString=JSON.stringify(cookieObj);setCookie(name,cookieString,minutes)}window.abd=window.abd||{};window.abd.status="noResponse";if(typeof window.abd.init==="undefined")window.abd.status="abEnabled";else(function waitForBody(){if(document.readyState.match(/interactive|complete/i)){window.abd.init({debug:false,found:function(){window.abd.status="abEnabled";updateCookie("s_abd",true,129600)},notFound:function(){window.abd.status="abDisabled";updateCookie("s_abd",
false,129600)}});return}setTimeout(waitForBody,25)})()},1417006,377897,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.Cookies=function(){return{domain:""||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"").split("\x3d");if(e[0]==a)return c?e[1]:decodeURIComponent(e[1])}return""},set:function(a,c,b){document.cookie=a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+Bootstrapper.Cookies.domain+
(/https:/.test(location.protocol)===true?";secure":";");return Bootstrapper.Cookies.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}();Bootstrapper.getQueryParam=function(key,loc){if(!this.params||loc){var search=loc||window.location.search;var params=search.replace(/^\?/,""),paramObj={};params=params.split("\x26");for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=paramObj;else return paramObj[key]||""}return this.params[key]||""};Bootstrapper.propertyWatcher=
function(options){var _private={watchers:[]};var _public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;_public.options=options;_public.change=function(oldVal,newVal){};return _public};_private.doChecks=function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i];var p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,
p);w.lastValue=p;if(w.options)if(w.options.stopOnReturn)_private.watchers.splice(i,1)}}_private.resetTimer()};_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);return w};_public={create:_private.addWatcher};_private.doChecks();return _public}();Bootstrapper.safeIframeInsert=function(u){var newFrame=document.createElement("iframe");newFrame.src=
u;newFrame.width=newFrame.height="1px";newFrame.style.display="none";var rand=parseInt(1E5*1E4*Math.random()*Math.random());Bootstrapper["appendFrame"+rand]=setInterval(function(a,b){return function(){document.getElementsByTagName("body")&&0<document.getElementsByTagName("body").length&&(clearInterval(Bootstrapper["appendFrame"+b]),document.getElementsByTagName("body")[0].appendChild(a))}}(newFrame,rand),250)};Bootstrapper.crypto={};!function(t){function h(t,h){h?(p[0]=p[16]=p[1]=p[2]=p[3]=p[4]=p[5]=
p[6]=p[7]=p[8]=p[9]=p[10]=p[11]=p[12]=p[13]=p[14]=p[15]=0,this.blocks=p):this.blocks=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],t?(this.h0=3238371032,this.h1=914150663,this.h2=812702999,this.h3=4144912697,this.h4=4290775857,this.h5=1750603025,this.h6=1694076839,this.h7=3204075428):(this.h0=1779033703,this.h1=3144134277,this.h2=1013904242,this.h3=2773480762,this.h4=1359893119,this.h5=2600822924,this.h6=528734635,this.h7=1541459225),this.block=this.start=this.bytes=0,this.finalized=this.hashed=!1,this.first=
!0,this.is224=t}var i=t,s=!i.JS_SHA256_NO_NODE_JS&&"object"==typeof process&&process.versions&&process.versions.node;s&&(i=global);var e=!i.JS_SHA256_NO_COMMON_JS&&"object"==typeof module&&module.exports,r="function"==typeof define&&define.amd,n="undefined"!=typeof ArrayBuffer,o="0123456789abcdef".split(""),a=[-2147483648,8388608,32768,128],f=[24,16,8,0],u=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,
2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,
2756734187,3204031479,3329325298],c=["hex","array","digest","arrayBuffer"],p=[],d=function(t,i){return function(s){return(new h(i,!0)).update(s)[t]()}},y=function(t){var i=d("hex",t);s&&(i=l(i,t)),i.create=function(){return new h(t)},i.update=function(t){return i.create().update(t)};for(var e=0;e<c.length;++e){var r=c[e];i[r]=d(r,t)}return i},l=function(t,h){var i=require("crypto"),s=require("buffer").Buffer,e=h?"sha224":"sha256";return function(h){if("string"==typeof h)return i.createHash(e).update(h,
"utf8").digest("hex");if(n&&h instanceof ArrayBuffer)h=new Uint8Array(h);else if(void 0===h.length)return t(h);return i.createHash(e).update(new s(h)).digest("hex")}};h.prototype.update=function(t){if(!this.finalized){var h="string"!=typeof t;h&&n&&t instanceof i.ArrayBuffer&&(t=new Uint8Array(t));for(var s,e,r=0,o=t.length||0,a=this.blocks;r<o;){if(this.hashed&&(this.hashed=!1,a[0]=this.block,a[16]=a[1]=a[2]=a[3]=a[4]=a[5]=a[6]=a[7]=a[8]=a[9]=a[10]=a[11]=a[12]=a[13]=a[14]=a[15]=0),h)for(e=this.start;r<
o&&e<64;++r)a[e>>2]|=t[r]<<f[3&e++];else for(e=this.start;r<o&&e<64;++r)(s=t.charCodeAt(r))<128?a[e>>2]|=s<<f[3&e++]:s<2048?(a[e>>2]|=(192|s>>6)<<f[3&e++],a[e>>2]|=(128|63&s)<<f[3&e++]):s<55296||s>=57344?(a[e>>2]|=(224|s>>12)<<f[3&e++],a[e>>2]|=(128|s>>6&63)<<f[3&e++],a[e>>2]|=(128|63&s)<<f[3&e++]):(s=65536+((1023&s)<<10|1023&t.charCodeAt(++r)),a[e>>2]|=(240|s>>18)<<f[3&e++],a[e>>2]|=(128|s>>12&63)<<f[3&e++],a[e>>2]|=(128|s>>6&63)<<f[3&e++],a[e>>2]|=(128|63&s)<<f[3&e++]);this.lastByteIndex=e,this.bytes+=
e-this.start,e>=64?(this.block=a[16],this.start=e-64,this.hash(),this.hashed=!0):this.start=e}return this}},h.prototype.finalize=function(){if(!this.finalized){this.finalized=!0;var t=this.blocks,h=this.lastByteIndex;t[16]=this.block,t[h>>2]|=a[3&h],this.block=t[16],h>=56&&(this.hashed||this.hash(),t[0]=this.block,t[16]=t[1]=t[2]=t[3]=t[4]=t[5]=t[6]=t[7]=t[8]=t[9]=t[10]=t[11]=t[12]=t[13]=t[14]=t[15]=0),t[15]=this.bytes<<3,this.hash()}},h.prototype.hash=function(){var t,h,i,s,e,r,n,o,a,f=this.h0,c=
this.h1,p=this.h2,d=this.h3,y=this.h4,l=this.h5,b=this.h6,v=this.h7,g=this.blocks;for(t=16;t<64;++t)h=((e=g[t-15])>>>7|e<<25)^(e>>>18|e<<14)^e>>>3,i=((e=g[t-2])>>>17|e<<15)^(e>>>19|e<<13)^e>>>10,g[t]=g[t-16]+h+g[t-7]+i<<0;for(a=c&p,t=0;t<64;t+=4)this.first?(this.is224?(r=300032,v=(e=g[0]-1413257819)-150054599<<0,d=e+24177077<<0):(r=704751109,v=(e=g[0]-210244248)-1521486534<<0,d=e+143694565<<0),this.first=!1):(h=(f>>>2|f<<30)^(f>>>13|f<<19)^(f>>>22|f<<10),s=(r=f&c)^f&p^a,v=d+(e=v+(i=(y>>>6|y<<26)^
(y>>>11|y<<21)^(y>>>25|y<<7))+(y&l^~y&b)+u[t]+g[t])<<0,d=e+(h+s)<<0),h=(d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10),s=(n=d&f)^d&c^r,b=p+(e=b+(i=(v>>>6|v<<26)^(v>>>11|v<<21)^(v>>>25|v<<7))+(v&y^~v&l)+u[t+1]+g[t+1])<<0,h=((p=e+(h+s)<<0)>>>2|p<<30)^(p>>>13|p<<19)^(p>>>22|p<<10),s=(o=p&d)^p&f^n,l=c+(e=l+(i=(b>>>6|b<<26)^(b>>>11|b<<21)^(b>>>25|b<<7))+(b&v^~b&y)+u[t+2]+g[t+2])<<0,h=((c=e+(h+s)<<0)>>>2|c<<30)^(c>>>13|c<<19)^(c>>>22|c<<10),s=(a=c&p)^c&d^o,y=f+(e=y+(i=(l>>>6|l<<26)^(l>>>11|l<<21)^(l>>>25|l<<
7))+(l&b^~l&v)+u[t+3]+g[t+3])<<0,f=e+(h+s)<<0;this.h0=this.h0+f<<0,this.h1=this.h1+c<<0,this.h2=this.h2+p<<0,this.h3=this.h3+d<<0,this.h4=this.h4+y<<0,this.h5=this.h5+l<<0,this.h6=this.h6+b<<0,this.h7=this.h7+v<<0},h.prototype.hex=function(){this.finalize();var t=this.h0,h=this.h1,i=this.h2,s=this.h3,e=this.h4,r=this.h5,n=this.h6,a=this.h7,f=o[t>>28&15]+o[t>>24&15]+o[t>>20&15]+o[t>>16&15]+o[t>>12&15]+o[t>>8&15]+o[t>>4&15]+o[15&t]+o[h>>28&15]+o[h>>24&15]+o[h>>20&15]+o[h>>16&15]+o[h>>12&15]+o[h>>8&
15]+o[h>>4&15]+o[15&h]+o[i>>28&15]+o[i>>24&15]+o[i>>20&15]+o[i>>16&15]+o[i>>12&15]+o[i>>8&15]+o[i>>4&15]+o[15&i]+o[s>>28&15]+o[s>>24&15]+o[s>>20&15]+o[s>>16&15]+o[s>>12&15]+o[s>>8&15]+o[s>>4&15]+o[15&s]+o[e>>28&15]+o[e>>24&15]+o[e>>20&15]+o[e>>16&15]+o[e>>12&15]+o[e>>8&15]+o[e>>4&15]+o[15&e]+o[r>>28&15]+o[r>>24&15]+o[r>>20&15]+o[r>>16&15]+o[r>>12&15]+o[r>>8&15]+o[r>>4&15]+o[15&r]+o[n>>28&15]+o[n>>24&15]+o[n>>20&15]+o[n>>16&15]+o[n>>12&15]+o[n>>8&15]+o[n>>4&15]+o[15&n];return this.is224||(f+=o[a>>
28&15]+o[a>>24&15]+o[a>>20&15]+o[a>>16&15]+o[a>>12&15]+o[a>>8&15]+o[a>>4&15]+o[15&a]),f},h.prototype.toString=h.prototype.hex,h.prototype.digest=function(){this.finalize();var t=this.h0,h=this.h1,i=this.h2,s=this.h3,e=this.h4,r=this.h5,n=this.h6,o=this.h7,a=[t>>24&255,t>>16&255,t>>8&255,255&t,h>>24&255,h>>16&255,h>>8&255,255&h,i>>24&255,i>>16&255,i>>8&255,255&i,s>>24&255,s>>16&255,s>>8&255,255&s,e>>24&255,e>>16&255,e>>8&255,255&e,r>>24&255,r>>16&255,r>>8&255,255&r,n>>24&255,n>>16&255,n>>8&255,255&
n];return this.is224||a.push(o>>24&255,o>>16&255,o>>8&255,255&o),a},h.prototype.array=h.prototype.digest,h.prototype.arrayBuffer=function(){this.finalize();var t=new ArrayBuffer(this.is224?28:32),h=new DataView(t);return h.setUint32(0,this.h0),h.setUint32(4,this.h1),h.setUint32(8,this.h2),h.setUint32(12,this.h3),h.setUint32(16,this.h4),h.setUint32(20,this.h5),h.setUint32(24,this.h6),this.is224||h.setUint32(28,this.h7),t};var b=y();b.sha256=b,b.sha224=y(!0),e?module.exports=b:(i.sha256=b.sha256,i.sha224=
b.sha224,r&&define(function(){return b}))}(Bootstrapper.crypto);!function(n){function t(n,t){var r=(65535&n)+(65535&t);return(n>>16)+(t>>16)+(r>>16)<<16|65535&r}function r(n,t){return n<<t|n>>>32-t}function e(n,e,o,u,c,f){return t(r(t(t(e,n),t(u,f)),c),o)}function o(n,t,r,o,u,c,f){return e(t&r|~t&o,n,t,u,c,f)}function u(n,t,r,o,u,c,f){return e(t&o|r&~o,n,t,u,c,f)}function c(n,t,r,o,u,c,f){return e(t^r^o,n,t,u,c,f)}function f(n,t,r,o,u,c,f){return e(r^(t|~o),n,t,u,c,f)}function i(n,r){n[r>>5]|=128<<
r%32,n[14+(r+64>>>9<<4)]=r;var e,i,a,d,h,l=1732584193,g=-271733879,p=-1732584194,v=271733878;for(e=0;e<n.length;e+=16)i=l,a=g,d=p,h=v,g=f(g=f(g=f(g=f(g=c(g=c(g=c(g=c(g=u(g=u(g=u(g=u(g=o(g=o(g=o(g=o(g,p=o(p,v=o(v,l=o(l,g,p,v,n[e],7,-680876936),g,p,n[e+1],12,-389564586),l,g,n[e+2],17,606105819),v,l,n[e+3],22,-1044525330),p=o(p,v=o(v,l=o(l,g,p,v,n[e+4],7,-176418897),g,p,n[e+5],12,1200080426),l,g,n[e+6],17,-1473231341),v,l,n[e+7],22,-45705983),p=o(p,v=o(v,l=o(l,g,p,v,n[e+8],7,1770035416),g,p,n[e+9],12,
-1958414417),l,g,n[e+10],17,-42063),v,l,n[e+11],22,-1990404162),p=o(p,v=o(v,l=o(l,g,p,v,n[e+12],7,1804603682),g,p,n[e+13],12,-40341101),l,g,n[e+14],17,-1502002290),v,l,n[e+15],22,1236535329),p=u(p,v=u(v,l=u(l,g,p,v,n[e+1],5,-165796510),g,p,n[e+6],9,-1069501632),l,g,n[e+11],14,643717713),v,l,n[e],20,-373897302),p=u(p,v=u(v,l=u(l,g,p,v,n[e+5],5,-701558691),g,p,n[e+10],9,38016083),l,g,n[e+15],14,-660478335),v,l,n[e+4],20,-405537848),p=u(p,v=u(v,l=u(l,g,p,v,n[e+9],5,568446438),g,p,n[e+14],9,-1019803690),
l,g,n[e+3],14,-187363961),v,l,n[e+8],20,1163531501),p=u(p,v=u(v,l=u(l,g,p,v,n[e+13],5,-1444681467),g,p,n[e+2],9,-51403784),l,g,n[e+7],14,1735328473),v,l,n[e+12],20,-1926607734),p=c(p,v=c(v,l=c(l,g,p,v,n[e+5],4,-378558),g,p,n[e+8],11,-2022574463),l,g,n[e+11],16,1839030562),v,l,n[e+14],23,-35309556),p=c(p,v=c(v,l=c(l,g,p,v,n[e+1],4,-1530992060),g,p,n[e+4],11,1272893353),l,g,n[e+7],16,-155497632),v,l,n[e+10],23,-1094730640),p=c(p,v=c(v,l=c(l,g,p,v,n[e+13],4,681279174),g,p,n[e],11,-358537222),l,g,n[e+
3],16,-722521979),v,l,n[e+6],23,76029189),p=c(p,v=c(v,l=c(l,g,p,v,n[e+9],4,-640364487),g,p,n[e+12],11,-421815835),l,g,n[e+15],16,530742520),v,l,n[e+2],23,-995338651),p=f(p,v=f(v,l=f(l,g,p,v,n[e],6,-198630844),g,p,n[e+7],10,1126891415),l,g,n[e+14],15,-1416354905),v,l,n[e+5],21,-57434055),p=f(p,v=f(v,l=f(l,g,p,v,n[e+12],6,1700485571),g,p,n[e+3],10,-1894986606),l,g,n[e+10],15,-1051523),v,l,n[e+1],21,-2054922799),p=f(p,v=f(v,l=f(l,g,p,v,n[e+8],6,1873313359),g,p,n[e+15],10,-30611744),l,g,n[e+6],15,-1560198380),
v,l,n[e+13],21,1309151649),p=f(p,v=f(v,l=f(l,g,p,v,n[e+4],6,-145523070),g,p,n[e+11],10,-1120210379),l,g,n[e+2],15,718787259),v,l,n[e+9],21,-343485551),l=t(l,i),g=t(g,a),p=t(p,d),v=t(v,h);return[l,g,p,v]}function a(n){var t,r="",e=32*n.length;for(t=0;t<e;t+=8)r+=String.fromCharCode(n[t>>5]>>>t%32&255);return r}function d(n){var t,r=[];for(r[(n.length>>2)-1]=void 0,t=0;t<r.length;t+=1)r[t]=0;var e=8*n.length;for(t=0;t<e;t+=8)r[t>>5]|=(255&n.charCodeAt(t/8))<<t%32;return r}function h(n){return a(i(d(n),
8*n.length))}function l(n,t){var r,e,o=d(n),u=[],c=[];for(u[15]=c[15]=void 0,o.length>16&&(o=i(o,8*n.length)),r=0;r<16;r+=1)u[r]=909522486^o[r],c[r]=1549556828^o[r];return e=i(u.concat(d(t)),512+8*t.length),a(i(c.concat(e),640))}function g(n){var t,r,e="";for(r=0;r<n.length;r+=1)t=n.charCodeAt(r),e+="0123456789abcdef".charAt(t>>>4&15)+"0123456789abcdef".charAt(15&t);return e}function p(n){return unescape(encodeURIComponent(n))}function v(n){return h(p(n))}function m(n){return g(v(n))}function s(n,
t){return l(p(n),p(t))}function C(n,t){return g(s(n,t))}function A(n,t,r){return t?r?s(t,n):C(t,n):r?v(n):m(n)}"function"==typeof define&&define.amd?define(function(){return A}):"object"==typeof module&&module.exports?module.exports=A:n.md5=A}(Bootstrapper.crypto)},2903010,271036,622);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(document.location.hostname.match(/subscription(\.|\-)(qa[1-9]\.)?(sfchronicle|timesunion|expressnews|houstonchronicle|hearstmediatx|hearstmediact|hearstnp)\.com/)){if(typeof window.ensFirstPage=="undefined")window.addEventListener("CasperAnalyticsEvent",function(e){if(!window.exData)window.exData=e;if(!window.ensFirstPage){console.log("*** Following data was stored in window.exData:");
console.log(window.exData)}window.ensFirstPage=true},{once:true});if(typeof window.siteBrand==="undefined"){window.siteBrand="none";if(typeof Bootstrapper.getQueryParam!="undefined")if(Bootstrapper.getQueryParam("siteId")!=="")window.siteBrand=Bootstrapper.getQueryParam("siteId").toUpperCase();else if(Bootstrapper.getQueryParam("siteid")!=="")window.siteBrand=Bootstrapper.getQueryParam("siteid").toUpperCase();else if(Bootstrapper.getQueryParam("siteID")!=="")window.siteBrand=Bootstrapper.getQueryParam("siteID").toUpperCase();
else{if(Bootstrapper.getQueryParam("SITEID")!=="")window.siteBrand=Bootstrapper.getQueryParam("SITEID").toUpperCase()}else{var urlParams=new URLSearchParams(window.location.search);if(urlParams.get("siteId")!=="")window.siteBrand=urlParams.get("siteId").toUpperCase();else if(urlParams.get("siteid")!=="")window.siteBrand=urlParams.get("siteid").toUpperCase();else if(urlParams.get("siteID")!=="")window.siteBrand=urlParams.get("siteID").toUpperCase();else if(urlParams.get("SITEID")!=="")window.siteBrand=
urlParams.get("SITEID").toUpperCase()}if(window.siteBrand=="none")if(document.location.hostname.match("sfchronicle.com"))window.siteBrand="SFC";else if(document.location.hostname.match("timesunion.com"))window.siteBrand="NY_ATU";else if(document.location.hostname.match("expressnews.com"))window.siteBrand="SA_SAEN";else if(document.location.hostname.match("houstonchronicle.com"))window.siteBrand="HC_HC";else if(document.location.hostname.match("hearstmediatx.com"))window.siteBrand="BE_BE";else if(document.location.hostname.match("hearstmediact.com"))window.siteBrand=
"CT_INS";else if(document.location.hostname.match("hearstnp.com"))window.siteBrand="MI_MDN"}}},3682605,615034,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(document.location.hostname.match(/(education|healthyeating|homeguides|livehealthy|smallbusiness|work)\.(chron|seattlepi|sfgate)\.com/))window.addEventListener("message",function(event){if(event.data.type=="s2nEvent"&&event.data.s2nEvent=="readyToPlay"){console.log("is s2nEvent with readyToPlay");console.log("start s2nData");console.log(window.s2nData);console.log("end s2nData");
if(!window.s2nData){console.log("set s2nReadyCheck");window.s2nReadyCheck={isReady:true,playerKey:event.data.playerKey,readyTime:Math.round(performance.now()/1E3,2)};console.log("read s2nReadyCheck");console.log(window.s2nReadyCheck)}}})},3168996,621567,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;commerceConnectorAnalytics=function(){window.HDN=window.HDN||{};window.HDN.dataLayer=window.HDN.dataLayer||{};window.HDN.dataLayer.site=window.HDN.dataLayer.site||{};if(!window.HDN.dataLayer.site.skimlinksPublisherId||!window.HDN.dataLayer.site.amazonTag){var domain=document.location.hostname;var domainConfig={"livehealthy.chron.com":{"amazonTag":"hearstnp-leaf-livehealthy-20",
"skimlinksPublisherId":"131678X1659754"},"smallbusiness.chron.com":{"amazonTag":"hearstnp-leaf-smallbusiness-20","skimlinksPublisherId":"131678X1635719"},"work.chron.com":{"amazonTag":"hearstnp-leaf-work-20","skimlinksPublisherId":"131678X1635718"},"education.seattlepi.com":{"amazonTag":"hearstnp-leaf-education-20","skimlinksPublisherId":"131678X1659753"},"healthyeating.sfgate.com":{"amazonTag":"hearstnp-leaf-healthyeating-20","skimlinksPublisherId":"131678X1656470"},"homeguides.sfgate.com":{"amazonTag":"hearstnp-leaf-homeguides-20",
"skimlinksPublisherId":"131678X1634560"}};if(domainConfig.hasOwnProperty(domain)){if(domainConfig[domain].amazonTag)window.HDN.dataLayer.site.amazonTag=domainConfig[domain].amazonTag;if(domainConfig[domain].skimlinksPublisherId)window.HDN.dataLayer.site.skimlinksPublisherId=domainConfig[domain].skimlinksPublisherId;console.log(domainConfig[domain],"hasOwnProperty",domainConfig.hasOwnProperty(domain))}}if(!window.HDN.dataLayer.site.amazonTag&&!window.HDN.dataLayer.site.skimlinksPublisherId)return;
window["__hrst_com_embed_debug"]=window.location.href.indexOf("debug\x3d1")>-1;var domainArr=document.location.hostname.split(".");var rootDomain=domainArr[domainArr.length-2]+"."+domainArr[domainArr.length-1];var cc_priorityList=["sfgate.com","chron.com","mysanantonio.com","seattlepi.com","timesunion.com","greenwichtime.com","stamfordadvocate.com","newstimes.com","ctpost.com","thehour.com","nhregister.com"];var cc_isPriority=cc_priorityList.includes(rootDomain);var commerceConnectorCustomCss="";
if(cc_isPriority)commerceConnectorCustomCss="https://www."+rootDomain+"/external/css/global.less.commerce_connector.css?"+Date.now();else commerceConnectorCustomCss="https://projects.hearstnp.com/projects/commerce-connector/styles/style.css?"+Date.now();window["__hrst_com_embed_setup"]={debug:window["__hrst_com_embed_debug"],custom_css:commerceConnectorCustomCss,fonts:["https://fonts.googleapis.com/css2?family\x3dLora:wght@400;600\x26family\x3dSource+Sans+Pro:wght@400;600\x26display\x3dswap"],onLoad:function(event){if(window["__hrst_com_embed_debug"])console.log("__hrst_com_embed_setup.onLoad",
this.data);var cDimWatcher=Bootstrapper.propertyWatcher.create(function(){var returnValue=false;if(typeof window.ga!=="undefined"&&typeof window.ga.getByName=="function"){hnpTrackerObj=window.ga.getByName("hnp");if(hnpTrackerObj!==undefined)if(typeof window.cDim!=="undefined"&&typeof window.cDim.ProductRetailerID!=="undefined")returnValue=true}return returnValue});var self=this;cDimWatcher.change=function(oldValue,newValue){if(newValue){var eventPayload={};eventPayload.nonInteraction=1;eventPayload.eventCategory=
"Product Display";eventPayload.eventAction=self.data.call_to_action;eventPayload.eventLabel=__hrst_com_embed_setup.toURLAmazon(self.data.url);eventPayload[window.cDim.ProductEmbedID]=self.data.id;eventPayload[window.cDim.ProductRetailerID]=self.data.product_retailer_id;eventPayload[window.cDim.ProductRetailerName]=self.data.retailer_name;eventPayload[window.cDim.ProductBrand]=self.data.brand;if(window["__hrst_com_embed_debug"])console.log("GA Event Payload",eventPayload);window.ga("hnp.send","event",
eventPayload);cDimWatcher={}}}},onClick:function(event){if(window["__hrst_com_embed_debug"]){console.log("__hrst_com_embed_setup.onClick data",this.data);console.log("__hrst_com_embed_setup.onClick event",event)}if(typeof window["ga"]==="function"&&typeof window.cDim==="object"){var buttonOrImage="Button";var callToAction=this.data.call_to_action;var tagType=event.target.tagName;if(tagType=="IMG"){buttonOrImage="Image";callToAction="IMAGE"}var eventPayload={};eventPayload.nonInteraction=0;eventPayload.eventCategory=
"Product "+buttonOrImage+" Click";eventPayload.eventAction=callToAction;eventPayload.eventLabel=__hrst_com_embed_setup.toURLAmazon(this.data.url);eventPayload[window.cDim.ProductEmbedID]=this.data.id;eventPayload[window.cDim.ProductRetailerID]=this.data.product_retailer_id;eventPayload[window.cDim.ProductRetailerName]=this.data.retailer_name;eventPayload[window.cDim.ProductBrand]=this.data.brand;if(window["__hrst_com_embed_debug"])console.log("GA Event Payload",eventPayload);window.ga("hnp.send",
"event",eventPayload)}else if(window["__hrst_com_embed_debug"])console.log("__hrst_com_embed_setup.onClick tried to fire BEFORE GA existed");if(window["__hrst_com_embed_debug"]){event.preventDefault();return false}},toURL:function(url){if(window["__hrst_com_embed_debug"])console.log("__hrst_com_embed_setup.toURL",url,this);if(window.HDN.dataLayer.site.amazonTag&&url.indexOf("https://www.amazon.com/")===0)url=__hrst_com_embed_setup.toURLAmazon(url);else if(window.HDN.dataLayer.site.skimlinksPublisherId){var urlObj=
new URL("https://go.redirectingat.com/");var paramsObj=new URLSearchParams(urlObj.search.slice(1));paramsObj.append("id",window.HDN.dataLayer.site.skimlinksPublisherId);paramsObj.append("url",url);paramsObj.append("sref",window.location.href);var gaTrackerId="";var gaClientId="";if(typeof window.ga!=="undefined"&&typeof window.ga.getByName=="function"){hnpTrackerObj=window.ga.getByName("hnp");if(hnpTrackerObj!==undefined)if(typeof window.cDim!=="undefined"&&typeof window.cDim.ProductRetailerID!==
"undefined"){gaTrackerId=hnpTrackerObj.get("trackingId");gaClientId=hnpTrackerObj.get("clientId")}}var xcustJson={"gaTrackerId":gaTrackerId,"gaClientId":gaClientId,"urlHash":Bootstrapper.mdHash,"roughTime":Date.now(),"price":this.data.price,"productName":this.data.headline,"productBrand":this.data.brand,"platform":"leaf"};var ipid="";if(Bootstrapper.getQueryParam("ipid"))ipid=Bootstrapper.getQueryParam("ipid");else if(Bootstrapper.getQueryParam("IPID"))ipid=Bootstrapper.getQueryParam("IPID");if(ipid)xcustJson.ipid=
ipid;xcustValue=JSON.stringify(xcustJson);if(window["__hrst_com_embed_debug"])console.log("new custom dimensions",xcustValue);paramsObj.append("xcust",xcustValue);urlObj.search="?"+paramsObj.toString();url=urlObj.toString()}return url},toURLAmazon:function(url){if(window.HDN.dataLayer.site.amazonTag&&url.indexOf("https://www.amazon.com/")===0){var urlObj=new URL(url);var paramsObj=new URLSearchParams(urlObj.search.slice(1));paramsObj.delete("tag");paramsObj.append("tag",window.HDN.dataLayer.site.amazonTag);
urlObj.search="?"+paramsObj.toString();url=urlObj.toString()}return url}}};commerceConnectorAnalytics()},3669079,704070,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.MD5=function(r,modify){if(modify===undefined)modify="";if(r===undefined)r=Math.random()*1E10+"||"+window.location.href+"||"+(new Date).getTime()+"||"+modify;function n(r,n){return r<<n|r>>>32-n}function t(r,n){var t,o,e,u,f;return e=2147483648&r,u=2147483648&n,t=1073741824&r,o=1073741824&n,f=(1073741823&r)+(1073741823&n),t&o?2147483648^f^e^u:t|o?1073741824&
f?3221225472^f^e^u:1073741824^f^e^u:f^e^u}function o(r,n,t){return r&n|~r&t}function e(r,n,t){return r&t|n&~t}function u(r,n,t){return r^n^t}function f(r,n,t){return n^(r|~t)}function i(r,e,u,f,i,a,c){return r=t(r,t(t(o(e,u,f),i),c)),t(n(r,a),e)}function a(r,o,u,f,i,a,c){return r=t(r,t(t(e(o,u,f),i),c)),t(n(r,a),o)}function c(r,o,e,f,i,a,c){return r=t(r,t(t(u(o,e,f),i),c)),t(n(r,a),o)}function C(r,o,e,u,i,a,c){return r=t(r,t(t(f(o,e,u),i),c)),t(n(r,a),o)}function g(r){for(var n,t=r.length,o=t+8,e=
(o-o%64)/64,u=16*(e+1),f=Array(u-1),i=0,a=0;t>a;)n=(a-a%4)/4,i=a%4*8,f[n]=f[n]|r.charCodeAt(a)<<i,a++;return n=(a-a%4)/4,i=a%4*8,f[n]=f[n]|128<<i,f[u-2]=t<<3,f[u-1]=t>>>29,f}function h(r){var n,t,o="",e="";for(t=0;3>=t;t++)n=r>>>8*t&255,e="0"+n.toString(16),o+=e.substr(e.length-2,2);return o}function d(r){r=r.replace(/\r\n/g,"\n");for(var n="",t=0;t<r.length;t++){var o=r.charCodeAt(t);128>o?n+=String.fromCharCode(o):o>127&&2048>o?(n+=String.fromCharCode(o>>6|192),n+=String.fromCharCode(63&o|128)):
(n+=String.fromCharCode(o>>12|224),n+=String.fromCharCode(o>>6&63|128),n+=String.fromCharCode(63&o|128))}return n}var v,S,m,l,s,A,p,y,b,w=Array(),B=7,D=12,L=17,M=22,j=5,k=9,q=14,x=20,z=4,E=11,F=16,G=23,H=6,I=10,J=15,K=21;for(r=d(r),w=g(r),A=1732584193,p=4023233417,y=2562383102,b=271733878,v=0;v<w.length;v+=16)S=A,m=p,l=y,s=b,A=i(A,p,y,b,w[v+0],B,3614090360),b=i(b,A,p,y,w[v+1],D,3905402710),y=i(y,b,A,p,w[v+2],L,606105819),p=i(p,y,b,A,w[v+3],M,3250441966),A=i(A,p,y,b,w[v+4],B,4118548399),b=i(b,A,p,
y,w[v+5],D,1200080426),y=i(y,b,A,p,w[v+6],L,2821735955),p=i(p,y,b,A,w[v+7],M,4249261313),A=i(A,p,y,b,w[v+8],B,1770035416),b=i(b,A,p,y,w[v+9],D,2336552879),y=i(y,b,A,p,w[v+10],L,4294925233),p=i(p,y,b,A,w[v+11],M,2304563134),A=i(A,p,y,b,w[v+12],B,1804603682),b=i(b,A,p,y,w[v+13],D,4254626195),y=i(y,b,A,p,w[v+14],L,2792965006),p=i(p,y,b,A,w[v+15],M,1236535329),A=a(A,p,y,b,w[v+1],j,4129170786),b=a(b,A,p,y,w[v+6],k,3225465664),y=a(y,b,A,p,w[v+11],q,643717713),p=a(p,y,b,A,w[v+0],x,3921069994),A=a(A,p,y,
b,w[v+5],j,3593408605),b=a(b,A,p,y,w[v+10],k,38016083),y=a(y,b,A,p,w[v+15],q,3634488961),p=a(p,y,b,A,w[v+4],x,3889429448),A=a(A,p,y,b,w[v+9],j,568446438),b=a(b,A,p,y,w[v+14],k,3275163606),y=a(y,b,A,p,w[v+3],q,4107603335),p=a(p,y,b,A,w[v+8],x,1163531501),A=a(A,p,y,b,w[v+13],j,2850285829),b=a(b,A,p,y,w[v+2],k,4243563512),y=a(y,b,A,p,w[v+7],q,1735328473),p=a(p,y,b,A,w[v+12],x,2368359562),A=c(A,p,y,b,w[v+5],z,4294588738),b=c(b,A,p,y,w[v+8],E,2272392833),y=c(y,b,A,p,w[v+11],F,1839030562),p=c(p,y,b,A,w[v+
14],G,4259657740),A=c(A,p,y,b,w[v+1],z,2763975236),b=c(b,A,p,y,w[v+4],E,1272893353),y=c(y,b,A,p,w[v+7],F,4139469664),p=c(p,y,b,A,w[v+10],G,3200236656),A=c(A,p,y,b,w[v+13],z,681279174),b=c(b,A,p,y,w[v+0],E,3936430074),y=c(y,b,A,p,w[v+3],F,3572445317),p=c(p,y,b,A,w[v+6],G,76029189),A=c(A,p,y,b,w[v+9],z,3654602809),b=c(b,A,p,y,w[v+12],E,3873151461),y=c(y,b,A,p,w[v+15],F,530742520),p=c(p,y,b,A,w[v+2],G,3299628645),A=C(A,p,y,b,w[v+0],H,4096336452),b=C(b,A,p,y,w[v+7],I,1126891415),y=C(y,b,A,p,w[v+14],J,
2878612391),p=C(p,y,b,A,w[v+5],K,4237533241),A=C(A,p,y,b,w[v+12],H,1700485571),b=C(b,A,p,y,w[v+3],I,2399980690),y=C(y,b,A,p,w[v+10],J,4293915773),p=C(p,y,b,A,w[v+1],K,2240044497),A=C(A,p,y,b,w[v+8],H,1873313359),b=C(b,A,p,y,w[v+15],I,4264355552),y=C(y,b,A,p,w[v+6],J,2734768916),p=C(p,y,b,A,w[v+13],K,1309151649),A=C(A,p,y,b,w[v+4],H,4149444226),b=C(b,A,p,y,w[v+11],I,3174756917),y=C(y,b,A,p,w[v+2],J,718787259),p=C(p,y,b,A,w[v+9],K,3951481745),A=t(A,S),p=t(p,m),y=t(y,l),b=t(b,s);var N=h(A)+h(p)+h(y)+
h(b);return N.toLowerCase()};try{window.Bootstrapper.mdHash=Bootstrapper.MD5()}catch(e){console.warn("Error Generating Unique Hash")}try{window.Bootstrapper.mdHash=typeof juiceMdHash==="undefined"?Bootstrapper.MD5():juiceMdHash;if(!/^(autos|mag|mos\-video|riddler)/.test(Bootstrapper.ensightenOptions.publishPath)){window.Bootstrapper.mdHashArray=[window.Bootstrapper.mdHash];for(var i=0;i<50;i++)window.Bootstrapper.mdHashArray.push(Bootstrapper.MD5(undefined,i))}}catch(e){console.warn("Error Generating Unique Hash")}},
3498804,374590,24);Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.HNP=window.HNP||{}},2837711,492548,24);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();